# Generated by Django 3.1.7 on 2021-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_garments', '0002_auto_20210326_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
