# Generated by Django 3.1.7 on 2021-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_garments', '0004_auto_20210406_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2020-4-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
